from ._shared import (
    oficio_documentos,
    oficio_documentos_gerar_todos,
    oficio_download_docx,
    oficio_download_ordem_servico_docx,
    oficio_download_ordem_servico_pdf,
    oficio_download_pdf,
    oficio_download_plano_trabalho_docx,
    oficio_download_plano_trabalho_pdf,
    oficio_download_termo_autorizacao,
    oficio_download_termo_autorizacao_pdf,
    ordem_servico_download_docx,
    ordem_servico_download_pdf,
    plano_trabalho_download_docx,
    plano_trabalho_download_pdf,
    termo_autorizacao_download_docx,
    termo_autorizacao_download_pdf,
)

__all__ = [
    "oficio_documentos",
    "oficio_documentos_gerar_todos",
    "oficio_download_docx",
    "oficio_download_pdf",
    "oficio_download_plano_trabalho_docx",
    "oficio_download_plano_trabalho_pdf",
    "oficio_download_ordem_servico_docx",
    "oficio_download_ordem_servico_pdf",
    "oficio_download_termo_autorizacao",
    "oficio_download_termo_autorizacao_pdf",
    "plano_trabalho_download_docx",
    "plano_trabalho_download_pdf",
    "ordem_servico_download_docx",
    "ordem_servico_download_pdf",
    "termo_autorizacao_download_docx",
    "termo_autorizacao_download_pdf",
]
