# Generated by Django 6.0.1 on 2026-01-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=120)),
                ('combustivel', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Viajante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('rg', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=120)),
            ],
        ),
    ]
