# Generated by Django 6.0.1 on 2026-01-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(max_length=50)),
                ('protocolo', models.CharField(max_length=80)),
                ('data', models.CharField(blank=True, max_length=50)),
                ('destino', models.CharField(max_length=200)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('roteiro_ida_saida_local', models.CharField(blank=True, max_length=200)),
                ('roteiro_ida_saida_datahora', models.CharField(blank=True, max_length=200)),
                ('roteiro_ida_chegada_local', models.CharField(blank=True, max_length=200)),
                ('roteiro_ida_chegada_datahora', models.CharField(blank=True, max_length=200)),
                ('roteiro_volta_saida_local', models.CharField(blank=True, max_length=200)),
                ('roteiro_volta_saida_datahora', models.CharField(blank=True, max_length=200)),
                ('roteiro_volta_chegada_local', models.CharField(blank=True, max_length=200)),
                ('roteiro_volta_chegada_datahora', models.CharField(blank=True, max_length=200)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('combustivel', models.CharField(blank=True, max_length=80)),
                ('motorista', models.CharField(blank=True, max_length=120)),
                ('motivo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='viagens.veiculo')),
                ('viajantes', models.ManyToManyField(blank=True, related_name='oficios', to='viagens.viajante')),
            ],
        ),
    ]
