# Generated by Django 6.0.1 on 2026-01-26 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_oficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_viajante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_motorista', to='viagens.viajante'),
        ),
        migrations.AddField(
            model_name='viajante',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='oficio',
            name='cidade_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_destino', to='viagens.cidade'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='cidade_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_sede', to='viagens.cidade'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='viagens.estado'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='estado_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_destino', to='viagens.estado'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='estado_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_sede', to='viagens.estado'),
        ),
    ]
