# Generated by Django 6.0.1 on 2026-01-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0003_cidade_estado_oficio_motorista_viajante_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trecho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("saida_data", models.DateField(blank=True, null=True)),
                ("saida_hora", models.TimeField(blank=True, null=True)),
                ("chegada_data", models.DateField(blank=True, null=True)),
                ("chegada_hora", models.TimeField(blank=True, null=True)),
                (
                    "destino_cidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trechos_destino",
                        to="viagens.cidade",
                    ),
                ),
                (
                    "destino_estado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trechos_destino",
                        to="viagens.estado",
                    ),
                ),
                (
                    "oficio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trechos",
                        to="viagens.oficio",
                    ),
                ),
                (
                    "origem_cidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trechos_origem",
                        to="viagens.cidade",
                    ),
                ),
                (
                    "origem_estado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trechos_origem",
                        to="viagens.estado",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
    ]
