# Generated by Django 6.0.1 on 2026-01-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='motorista_carona',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_protocolo',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
