# Generated by Django 6.0.1 on 2026-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0009_oficio_draft_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_chefia', models.CharField(default='Delegado Geral Adjunto', max_length=120)),
                ('cargo_chefia', models.CharField(default='Gabinete do Delegado Geral Adjunto', max_length=120)),
                ('orgao_origem', models.CharField(default='Assessoria de Comunicação Social', max_length=200)),
                ('orgao_destino_padrao', models.CharField(default='Gabinete do Delegado Geral Adjunto', max_length=200)),
                ('rodape', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Ofício',
                'verbose_name_plural': 'Configurações do Ofício',
            },
        ),
    ]
