# Generated by Django 6.0.1 on 2026-02-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0010_configuracaooficio'),
        ('viagens', '0010_veiculo_tipo_viatura'),
    ]

    operations = [
    ]
