# Generated by Django on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0011_merge_20260203_2010"),
    ]

    operations = [
        migrations.CreateModel(
            name="OficioConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("setor_nome", models.CharField(blank=True, default="", max_length=255)),
                ("cabecalho_linha3", models.CharField(default="", max_length=255)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="oficio_config/")),
                ("dest_tratamento", models.CharField(default="", max_length=50)),
                ("dest_nome", models.CharField(default="", max_length=255)),
                ("dest_cargo", models.CharField(default="", max_length=255)),
                ("rodape_setor_nome", models.CharField(default="", max_length=255)),
                ("rodape_endereco", models.TextField(blank=True, default="")),
                ("rodape_telefone", models.CharField(blank=True, default="", max_length=50)),
                ("rodape_email", models.EmailField(blank=True, default="", max_length=254)),
                ("texto_abertura", models.TextField(blank=True, default="")),
                ("texto_declaracao", models.TextField(blank=True, default="")),
                ("texto_encerramento", models.TextField(blank=True, default="")),
                ("custeio_texto_explicativo", models.TextField(blank=True, default="")),
                (
                    "custeio_tipo",
                    models.CharField(
                        choices=[("radio", "Radio (unico)"), ("checkbox", "Checkbox (multiplo)")],
                        default="radio",
                        max_length=20,
                    ),
                ),
                ("custeio_opcoes_json", models.JSONField(blank=True, default=list)),
                ("assinante_nome", models.CharField(default="", max_length=255)),
                ("assinante_cargo", models.CharField(default="", max_length=255)),
                ("assinante_matricula", models.CharField(blank=True, default="", max_length=80)),
                ("assinatura_imagem", models.ImageField(blank=True, null=True, upload_to="oficio_config/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracao do Oficio",
                "verbose_name_plural": "Configuracoes do Oficio",
            },
        ),
    ]
