# Generated by Django on 2026-02-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0012_oficio_config"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="setor_nome",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="cabecalho_linha3",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="logo",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="dest_tratamento",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="dest_nome",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="dest_cargo",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="rodape_setor_nome",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="rodape_endereco",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="rodape_telefone",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="rodape_email",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="texto_abertura",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="texto_declaracao",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="texto_encerramento",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="custeio_texto_explicativo",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="custeio_tipo",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="custeio_opcoes_json",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="assinante_nome",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="assinante_cargo",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="assinante_matricula",
                ),
                migrations.RemoveField(
                    model_name="oficioconfig",
                    name="assinatura_imagem",
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="unidade_nome",
                    field=models.CharField(default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="origem_nome",
                    field=models.CharField(default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="cep",
                    field=models.CharField(default="", max_length=9),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="logradouro",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="bairro",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="cidade",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="uf",
                    field=models.CharField(blank=True, default="", max_length=2),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="numero",
                    field=models.CharField(default="", max_length=30),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="complemento",
                    field=models.CharField(blank=True, default="", max_length=120),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="telefone",
                    field=models.CharField(blank=True, default="", max_length=50),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="email",
                    field=models.EmailField(blank=True, default="", max_length=254),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="assinante",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oficio_configs",
                        to="viagens.viajante",
                    ),
                ),
            ],
            database_operations=[
                migrations.AddField(
                    model_name="oficioconfig",
                    name="unidade_nome",
                    field=models.CharField(default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="origem_nome",
                    field=models.CharField(default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="cep",
                    field=models.CharField(default="", max_length=9),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="logradouro",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="bairro",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="cidade",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="uf",
                    field=models.CharField(blank=True, default="", max_length=2),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="numero",
                    field=models.CharField(default="", max_length=30),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="complemento",
                    field=models.CharField(blank=True, default="", max_length=120),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="telefone",
                    field=models.CharField(blank=True, default="", max_length=50),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="email",
                    field=models.EmailField(blank=True, default="", max_length=254),
                ),
                migrations.AddField(
                    model_name="oficioconfig",
                    name="assinante",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oficio_configs",
                        to="viagens.viajante",
                    ),
                ),
            ],
        ),
    ]
