# Generated by Django on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0013_oficio_config_rework"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="oficio",
            name="assunto_tipo",
            field=models.CharField(
                choices=[("AUTORIZACAO", "Autorizacao"), ("CONVALIDACAO", "Convalidacao")],
                default="AUTORIZACAO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="tipo_viatura",
            field=models.CharField(
                blank=True,
                choices=[("CARACTERIZADA", "Caracterizada"), ("DESCARACTERIZADA", "Descaracterizada")],
                default="DESCARACTERIZADA",
                max_length=20,
            ),
        ),
    ]
