# Generated by Django 6.0.1 on 2026-02-05 14:52

from django.db import migrations, models


def _create_assessor_cargo(apps, schema_editor):
    Cargo = apps.get_model("viagens", "Cargo")
    Cargo.objects.get_or_create(nome="Assessor de Comunicação Social")


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0015_destino_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="oficio",
            name="custos",
            field=models.CharField(
                choices=[
                    ("UNIDADE", "UNIDADE – DPC (diária e combustível serão custeados pela DPC)"),
                    ("OUTRA_INSTITUICAO", "OUTRA INSTITUIÇÃO"),
                    ("SEM_ONUS", "Com ônus limitados aos próprios vencimentos"),
                ],
                default="UNIDADE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="oficio",
            name="nome_instituicao_custeio",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.RunPython(_create_assessor_cargo, migrations.RunPython.noop),
    ]
