# Generated by Django 6.0.1 on 2026-02-05 00:00

from django.db import migrations, models


def _recalcular_destino(apps, schema_editor):
    Oficio = apps.get_model("viagens", "Oficio")
    Trecho = apps.get_model("viagens", "Trecho")

    for oficio in Oficio.objects.all():
        destino_code = "GAB"
        trechos = (
            Trecho.objects.filter(oficio=oficio)
            .select_related("destino_estado", "destino_cidade__estado")
        )
        for trecho in trechos:
            estado = trecho.destino_estado or (
                trecho.destino_cidade.estado if trecho.destino_cidade else None
            )
            if estado and (estado.sigla or "").strip().upper() != "PR":
                destino_code = "SESP"
                break
        if oficio.destino != destino_code:
            Oficio.objects.filter(pk=oficio.pk).update(destino=destino_code)


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0016_oficio_custos_oficio_nome_instituicao_custeio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oficio",
            name="destino",
            field=models.CharField(
                choices=[("GAB", "GABINETE DO DELEGADO GERAL ADJUNTO"), ("SESP", "SESP")],
                default="GAB",
                editable=False,
                max_length=40,
            ),
        ),
        migrations.RunPython(_recalcular_destino, migrations.RunPython.noop),
    ]
