# Generated by Django 6.0.1 on 2026-02-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0017_oficio_destino_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="oficio",
            name="carona_oficio_referencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oficios_que_usam_como_carona",
                to="viagens.oficio",
            ),
        ),
    ]
