# Generated by Django 6.0.1 on 2026-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0019_oficio_custeio_tipo_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaooficio',
            name='cargo_chefia',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='configuracaooficio',
            name='nome_chefia',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='configuracaooficio',
            name='orgao_destino_padrao',
            field=models.CharField(default='GABINETE DO DELEGADO GERAL ADJUNTO', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracaooficio',
            name='orgao_origem',
            field=models.CharField(default='ASSESSORIA DE COMUNICAÇÃO SOCIAL', max_length=200),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='custos',
            field=models.CharField(choices=[('UNIDADE', 'UNIDADE – DPC (diária e combustível serão custeados pela DPC).'), ('OUTRA_INSTITUICAO', 'OUTRA INSTITUIÇÃO'), ('SEM_ONUS', 'Com ônus limitados aos próprios vencimentos')], default='UNIDADE', max_length=20),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='tipo_viatura',
            field=models.CharField(blank=True, choices=[('CARACTERIZADA', 'Caracterizada'), ('DESCARACTERIZADA', 'Descaracterizada')], default='DESCARACTERIZADA', max_length=20),
        ),
    ]
