# Generated by Django 5.2.11 on 2026-02-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0020_alter_configuracaooficio_cargo_chefia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oficioconfig",
            name="sede_cidade_default",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oficio_config_sede_default",
                to="viagens.cidade",
            ),
        ),
        migrations.AlterField(
            model_name="oficio",
            name="custeio_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "UNIDADE",
                        "UNIDADE - DPC (diarias e combustivel serao custeados pela DPC).",
                    ),
                    ("OUTRA_INSTITUICAO", "OUTRA INSTITUICAO"),
                    ("ONUS_LIMITADOS", "ONUS LIMITADOS AOS PROPRIOS VENCIMENTOS"),
                ],
                default="UNIDADE",
                max_length=30,
            ),
        ),
    ]
