# Generated by Django 5.2.11 on 2026-02-10

import re
from datetime import date

from django.db import migrations, models


def _parse_oficio(raw_value):
    raw = (raw_value or "").strip().replace("\\", "/").replace(" ", "")
    raw = re.sub(r"[^0-9/]", "", raw)
    if not raw:
        return (None, None)
    if "/" in raw:
        left, right = raw.split("/", 1)
        numero = int(left) if left.isdigit() else None
        ano = int(right[-4:]) if right.isdigit() else None
        return (numero, ano)
    if raw.isdigit():
        return (int(raw), None)
    return (None, None)


def _backfill_oficio_numeracao(apps, schema_editor):
    Oficio = apps.get_model("viagens", "Oficio")
    OficioCounter = apps.get_model("viagens", "OficioCounter")

    current_year = date.today().year
    used_by_year = {}

    queryset = Oficio.objects.all().order_by("id")
    for oficio in queryset:
        numero, ano = _parse_oficio(getattr(oficio, "oficio", ""))
        base_year = current_year
        created_at = getattr(oficio, "created_at", None)
        if created_at:
            try:
                base_year = created_at.year
            except Exception:
                base_year = current_year
        ano = ano or base_year

        year_used = used_by_year.setdefault(int(ano), set())
        if not numero:
            numero = 1
            while numero in year_used:
                numero += 1
        else:
            numero = int(numero)
            if numero in year_used:
                candidate = numero
                while candidate in year_used:
                    candidate += 1
                numero = candidate

        year_used.add(numero)

        oficio.numero = numero
        oficio.ano = int(ano)
        oficio.oficio = f"{numero}/{ano}"

        motorista_numero, motorista_ano = _parse_oficio(
            getattr(oficio, "motorista_oficio", "")
        )
        if motorista_numero and not motorista_ano:
            motorista_ano = int(ano)
        if motorista_numero and motorista_ano:
            oficio.motorista_oficio_numero = int(motorista_numero)
            oficio.motorista_oficio_ano = int(motorista_ano)
            oficio.motorista_oficio = (
                f"{oficio.motorista_oficio_numero}/{oficio.motorista_oficio_ano}"
            )
        else:
            oficio.motorista_oficio_numero = None
            oficio.motorista_oficio_ano = None
            oficio.motorista_oficio = ""

        oficio.save(
            update_fields=[
                "numero",
                "ano",
                "oficio",
                "motorista_oficio_numero",
                "motorista_oficio_ano",
                "motorista_oficio",
            ]
        )

    for ano, numbers in used_by_year.items():
        if not numbers:
            continue
        OficioCounter.objects.update_or_create(
            ano=int(ano),
            defaults={"last_numero": max(numbers)},
        )


def _cleanup_orphan_trechos(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            """
            DELETE FROM viagens_trecho
            WHERE oficio_id NOT IN (SELECT id FROM viagens_oficio)
            """
        )
        cursor.execute(
            """
            UPDATE viagens_trecho
            SET origem_estado_id = NULL
            WHERE origem_estado_id IS NOT NULL
              AND origem_estado_id NOT IN (SELECT id FROM viagens_estado)
            """
        )
        cursor.execute(
            """
            UPDATE viagens_trecho
            SET origem_cidade_id = NULL
            WHERE origem_cidade_id IS NOT NULL
              AND origem_cidade_id NOT IN (SELECT id FROM viagens_cidade)
            """
        )
        cursor.execute(
            """
            UPDATE viagens_trecho
            SET destino_estado_id = NULL
            WHERE destino_estado_id IS NOT NULL
              AND destino_estado_id NOT IN (SELECT id FROM viagens_estado)
            """
        )
        cursor.execute(
            """
            UPDATE viagens_trecho
            SET destino_cidade_id = NULL
            WHERE destino_cidade_id IS NOT NULL
              AND destino_cidade_id NOT IN (SELECT id FROM viagens_cidade)
            """
        )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0021_oficioconfig_sede_cidade_default_and_more"),
    ]

    operations = [
        migrations.RunPython(_cleanup_orphan_trechos, _noop),
        migrations.CreateModel(
            name="OficioCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ano", models.IntegerField(unique=True)),
                ("last_numero", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="oficio",
            name="ano",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="oficio",
            name="motorista_oficio_ano",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oficio",
            name="motorista_oficio_numero",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oficio",
            name="numero",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(_backfill_oficio_numeracao, _noop),
        migrations.AddConstraint(
            model_name="oficio",
            constraint=models.UniqueConstraint(fields=("ano", "numero"), name="uniq_oficio_numero_por_ano"),
        ),
    ]
