# Generated by Django 6.0.1 on 2026-02-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0023_oficio_created_at_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('data_unica', models.BooleanField(default=False)),
                ('destinos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termo de autorizacao',
                'verbose_name_plural': 'Termos de autorizacao',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
