# Generated by Django 5.2.11 on 2026-02-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0023_oficio_created_at_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoAtividadeOpcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, unique=True)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Opcao de atividade do plano",
                "verbose_name_plural": "Opcoes de atividade do plano",
                "ordering": ["ordem", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="PlanoTrabalhoCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(unique=True)),
                ("last_numero", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="oficioconfig",
            name="plano_cargo_chefia",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="oficioconfig",
            name="plano_divisao",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="oficioconfig",
            name="plano_nome_chefia",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="oficioconfig",
            name="plano_sede",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="oficioconfig",
            name="plano_unidade",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="PlanoTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(db_index=True)),
                ("ano", models.PositiveIntegerField(db_index=True)),
                ("data_evento_inicio", models.DateField()),
                ("data_evento_fim", models.DateField()),
                ("fim_mesmo_dia", models.BooleanField(default=False)),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                ("metas", models.TextField(blank=True, default="")),
                ("incluir_microonibus", models.BooleanField(default=False)),
                ("atividades_selecionadas", models.JSONField(blank=True, default=list)),
                ("atividades_texto", models.TextField(blank=True, default="")),
                ("quantidade_servidores", models.PositiveIntegerField(default=1)),
                ("diarias_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destino_cidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_destino",
                        to="viagens.cidade",
                    ),
                ),
                (
                    "destino_estado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_destino",
                        to="viagens.estado",
                    ),
                ),
                (
                    "servidor_responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planos_responsavel",
                        to="viagens.viajante",
                    ),
                ),
            ],
            options={
                "ordering": ["-ano", "-numero", "-id"],
                "unique_together": {("numero", "ano")},
            },
        ),
    ]
