# Generated by Django 6.0.1 on 2026-02-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0024_termoautorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='justificativa_modelo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='oficio',
            name='justificativa_texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
