# Generated by Django 6.0.1 on 2026-02-25 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0025_oficio_justificativa_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('last_num', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoTrabalhoCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('last_num', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('referencia', models.CharField(default='Diligências', max_length=200)),
                ('determinante_nome', models.CharField(blank=True, default='', max_length=200)),
                ('determinante_cargo', models.CharField(blank=True, default='', max_length=200)),
                ('finalidade', models.TextField(blank=True, default='')),
                ('texto_override', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico', to='viagens.oficio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'numero'), name='uniq_ordem_servico_numero_por_ano')],
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('local', models.CharField(default='', max_length=120)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('efetivo_por_dia', models.PositiveIntegerField(default=0)),
                ('valor_total', models.CharField(blank=True, default='', max_length=120)),
                ('coordenador_nome', models.CharField(blank=True, default='', max_length=200)),
                ('coordenador_cargo', models.CharField(blank=True, default='', max_length=200)),
                ('texto_override', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_trabalho', to='viagens.oficio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'numero'), name='uniq_plano_trabalho_numero_por_ano')],
            },
        ),
    ]
