# Generated by Django 6.0.1 on 2026-02-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0026_ordemservicocounter_planotrabalhocounter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadorMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='composicao_diarias',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='contexto_solicitacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='coordenador_plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho_coordenados', to='viagens.viajante'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='destino',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='efetivo_formatado',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='estrutura_apoio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='horario_atendimento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='possui_coordenador_municipal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='programa_projeto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='quantidade_servidores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='sigla_unidade',
            field=models.CharField(blank=True, default='ASCOM', max_length=30),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='solicitante',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='valor_total_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='coordenador_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='viagens.coordenadormunicipal'),
        ),
        migrations.CreateModel(
            name='PlanoTrabalhoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(max_length=350)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='viagens.planotrabalho')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalhoLocalAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('data', models.DateField(blank=True, null=True)),
                ('local', models.CharField(max_length=240)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_atuacao', to='viagens.planotrabalho')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalhoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(max_length=350)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='viagens.planotrabalho')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalhoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(max_length=350)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='viagens.planotrabalho')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
    ]
