# Generated by Django 6.0.1 on 2026-02-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0027_coordenadormunicipal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='destinos_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='efetivo_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='solicitantes_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='unidade_movel',
            field=models.BooleanField(default=False),
        ),
    ]
