# Generated by Django 6.0.1 on 2026-02-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0028_planotrabalho_destinos_json_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ('ordem', 'nome')},
        ),
        migrations.AddField(
            model_name='cargo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='is_coordenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Efetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efetivo', to='viagens.cargo')),
            ],
            options={
                'ordering': ('cargo__ordem', 'cargo__nome'),
            },
        ),
    ]
