# Generated by Django 6.0.1 on 2026-03-02 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0029_alter_cargo_options_cargo_ativo_cargo_is_coordenador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcaoInstitucional",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=255, verbose_name="Titulo da Acao")),
                ("descricao", models.TextField(blank=True, verbose_name="Descricao Detalhada")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Acao Institucional",
                "verbose_name_plural": "Acoes Institucionais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="oficio",
            name="acao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oficios",
                to="viagens.acaoinstitucional",
                verbose_name="Acao Institucional",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="acao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordem_servico",
                to="viagens.acaoinstitucional",
                verbose_name="Acao Institucional",
            ),
        ),
        migrations.AddField(
            model_name="planotrabalho",
            name="acao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plano_trabalho",
                to="viagens.acaoinstitucional",
                verbose_name="Acao Institucional",
            ),
        ),
        migrations.AddField(
            model_name="termoautorizacao",
            name="acao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="termos",
                to="viagens.acaoinstitucional",
                verbose_name="Acao Institucional",
            ),
        ),
    ]
