# Generated by Django 6.0.1 on 2026-03-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0031_migrar_acao_institucional_dados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Roteiro')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('uf_origem', models.CharField(max_length=2, verbose_name='UF Origem')),
                ('cidade_origem', models.CharField(max_length=100, verbose_name='Cidade Origem')),
                ('uf_destino', models.CharField(max_length=2, verbose_name='UF Destino')),
                ('cidade_destino', models.CharField(max_length=100, verbose_name='Cidade Destino')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distancia (km)')),
                ('tipo_deslocamento', models.CharField(choices=[('INTERIOR', 'Interior'), ('CAPITAL', 'Capital'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Tipo de Deslocamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OficioRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculado_em', models.DateTimeField(auto_now_add=True, verbose_name='Vinculado em')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observacao')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiros_vinculados', to='viagens.oficio', verbose_name='Oficio')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficios_vinculados', to='viagens.roteiro', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Vinculo Oficio-Roteiro',
                'verbose_name_plural': 'Vinculos Oficio-Roteiro',
                'unique_together': {('oficio', 'roteiro')},
            },
        ),
        migrations.CreateModel(
            name='TrechoRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('uf_origem', models.CharField(max_length=2, verbose_name='UF Origem')),
                ('cidade_origem', models.CharField(max_length=100, verbose_name='Cidade Origem')),
                ('uf_destino', models.CharField(max_length=2, verbose_name='UF Destino')),
                ('cidade_destino', models.CharField(max_length=100, verbose_name='Cidade Destino')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distancia (km)')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='viagens.roteiro', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Trecho do Roteiro',
                'verbose_name_plural': 'Trechos do Roteiro',
                'ordering': ['roteiro', 'ordem', 'id'],
                'unique_together': {('roteiro', 'ordem')},
            },
        ),
    ]
