# Generated by Django 6.0.1 on 2026-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0032_criar_roteiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='trechoroteiro',
            name='modal',
            field=models.CharField(choices=[('veiculo_proprio', 'Veiculo Proprio'), ('veiculo_locado', 'Veiculo Locado'), ('onibus', 'Onibus'), ('aviao', 'Aviao'), ('outro', 'Outro')], default='veiculo_proprio', max_length=50),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
