# Generated by Django 6.0.1 on 2026-03-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0033_trechoroteiro_modal_trechoroteiro_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='roteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_como_roteiro', to='viagens.roteiro', verbose_name='Roteiro de Viagem'),
        ),
    ]
