# Generated by Django 6.0.1 on 2026-03-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0035_alter_roteiro_uf_destino_alter_roteiro_uf_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trechoroteiro',
            name='uf_destino',
            field=models.CharField(default='PR', max_length=2, verbose_name='UF Destino'),
        ),
        migrations.AlterField(
            model_name='trechoroteiro',
            name='uf_origem',
            field=models.CharField(default='PR', max_length=2, verbose_name='UF Origem'),
        ),
    ]
