# Generated by Django 6.0.1 on 2026-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0036_alter_trechoroteiro_uf_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='retorno_chegada_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_chegada_hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_saida_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_saida_hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='chegada_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='chegada_hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='saida_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='saida_hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
