# Generated by Django 6.0.1 on 2026-03-02 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0037_roteiro_retorno_chegada_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='cidade_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros_sede_cidade', to='viagens.cidade'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='estado_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros_sede_estado', to='viagens.estado'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_chegada_cidade',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='retorno_saida_cidade',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='destino_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_roteiro_destino_cidade', to='viagens.cidade'),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='destino_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_roteiro_destino_estado', to='viagens.estado'),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='origem_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_roteiro_origem_cidade', to='viagens.cidade'),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='origem_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trechos_roteiro_origem_estado', to='viagens.estado'),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='nome',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nome do Roteiro'),
        ),
    ]
