# Generated by Django 6.0.1 on 2026-03-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0038_refatorar_roteiro_viagem_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trechoroteiro',
            name='tempo_viagem_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo estimado em minutos', null=True),
        ),
    ]
