# Generated by Django 6.0.1 on 2026-03-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0039_trechoroteiro_tempo_viagem_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trechoroteiro',
            name='retorno_chegada_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='retorno_chegada_hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='retorno_saida_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trechoroteiro',
            name='retorno_saida_hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
