# Generated by Django 6.0.1 on 2026-03-03 01:07

import datetime
from django.db import migrations, models


def _backfill_tempo_viagem(apps, schema_editor):
    Roteiro = apps.get_model("viagens", "Roteiro")
    TrechoRoteiro = apps.get_model("viagens", "TrechoRoteiro")

    for roteiro in Roteiro.objects.filter(tempo_viagem__isnull=True).iterator():
        trecho = (
            TrechoRoteiro.objects.filter(
                roteiro=roteiro,
                tempo_viagem_minutos__isnull=False,
            )
            .order_by("ordem", "id")
            .first()
        )
        if not trecho:
            continue

        total_minutos = int(trecho.tempo_viagem_minutos or 0)
        if total_minutos < 0 or total_minutos >= (24 * 60):
            continue

        horas, minutos = divmod(total_minutos, 60)
        roteiro.tempo_viagem = datetime.time(hour=horas, minute=minutos)
        roteiro.save(update_fields=["tempo_viagem"])


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0040_trechoroteiro_retorno_chegada_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='tempo_viagem',
            field=models.TimeField(blank=True, help_text='Duracao no formato HH:MM', null=True),
        ),
        migrations.RunPython(_backfill_tempo_viagem, migrations.RunPython.noop),
    ]
