# Generated by Django 6.0.1 on 2026-03-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0041_roteiro_tempo_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='criado_automaticamente',
            field=models.BooleanField(default=False, help_text='True quando o roteiro e clonado automaticamente ao ser alterado no contexto de um oficio.'),
        ),
    ]
