# Generated by Django 6.0.1 on 2026-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0042_roteiro_criado_automaticamente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloJustificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de justificativa',
                'verbose_name_plural': 'Modelos de justificativa',
                'ordering': ('ordem', 'label'),
            },
        ),
    ]
