# Generated by Django 6.0.3 — manual fix for M2M through model transition
import django.db.models.deletion
from django.db import migrations, models


def copy_oficio_viajantes(apps, schema_editor):
    """Copia dados da tabela M2M auto-gerada para a nova tabela OficioViajante."""
    db = schema_editor.connection.alias
    schema_editor.connection.ensure_connection()
    cursor = schema_editor.connection.cursor()
    # Verifica se a tabela antiga ainda existe (apenas durante a transição)
    try:
        cursor.execute(
            "INSERT INTO viagens_oficioviajante (oficio_id, viajante_id, ordem, nome_snapshot, cargo_snapshot, unidade_snapshot) "
            "SELECT oficio_id, viajante_id, 0, '', '', '' "
            "FROM viagens_oficio_viajantes"
        )
    except Exception:
        # Tabela antiga pode não existir em instalações novas
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0055_termo_oficio_dispensado_logistica'),
    ]

    operations = [
        # 1. Criar novos modelos independentes
        migrations.CreateModel(
            name='ModeloMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=200, verbose_name='Rótulo')),
                ('texto', models.TextField(verbose_name='Texto do motivo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
            ],
            options={
                'verbose_name': 'Modelo de Motivo',
                'verbose_name_plural': 'Modelos de Motivo',
                'ordering': ['ordem', 'label'],
            },
        ),
        # 2. Criar tabela OficioViajante (intermediária explícita) — SEM FKs ainda
        migrations.CreateModel(
            name='OficioViajante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('nome_snapshot', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome (snapshot)')),
                ('cargo_snapshot', models.CharField(blank=True, default='', max_length=200, verbose_name='Cargo (snapshot)')),
                ('unidade_snapshot', models.CharField(blank=True, default='', max_length=200, verbose_name='Unidade (snapshot)')),
            ],
            options={
                'verbose_name': 'Viajante do Ofício',
                'verbose_name_plural': 'Viajantes do Ofício',
                'ordering': ['ordem', 'id'],
            },
        ),
        # 3. Criar modelo RoteiroDestino (sem FKs ainda)
        migrations.CreateModel(
            name='RoteiroDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do destino')),
                ('principal', models.BooleanField(default=False, verbose_name='Destino principal')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Destino do Roteiro',
                'verbose_name_plural': 'Destinos do Roteiro',
                'ordering': ['ordem', 'id'],
            },
        ),
        # 4. Adicionar FKs à OficioViajante
        migrations.AddField(
            model_name='oficioviajante',
            name='oficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficio_viajantes', to='viagens.oficio', verbose_name='Ofício'),
        ),
        migrations.AddField(
            model_name='oficioviajante',
            name='viajante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficio_viajantes', to='viagens.viajante', verbose_name='Viajante'),
        ),
        migrations.AlterUniqueTogether(
            name='oficioviajante',
            unique_together={('oficio', 'viajante')},
        ),
        # 5. Copiar dados da tabela M2M auto-gerada para a nova OficioViajante
        migrations.RunPython(copy_oficio_viajantes, migrations.RunPython.noop),
        # 6. Remover o campo M2M antigo (sem through) — dropa a tabela auto-gerada
        migrations.RemoveField(
            model_name='oficio',
            name='viajantes',
        ),
        # 7. Adicionar o novo campo M2M com through=OficioViajante
        migrations.AddField(
            model_name='oficio',
            name='viajantes',
            field=models.ManyToManyField(blank=True, related_name='oficios', through='viagens.OficioViajante', to='viagens.viajante'),
        ),
        # 8. Ajustar constraint no TermoAutorizacao (detectado pelo makemigrations)
        migrations.RemoveConstraint(
            model_name='termoautorizacao',
            name='uniq_termo_oficio_viajante_ativo',
        ),
        migrations.AlterField(
            model_name='documentoeventoarquivo',
            name='tipo',
            field=models.CharField(choices=[('OFICIO_ASSINADO', 'Ofício assinado'), ('SOLICITACAO_FORMAL_ASSINADA', 'Solicitação formal (convite/ofício) assinada'), ('PLANO_ASSINADO', 'Plano de trabalho assinado'), ('ORDEM_ASSINADO', 'Ordem de serviço assinada'), ('JUSTIFICATIVA_ASSINADA', 'Justificativa assinada'), ('TERMO_ASSINADO', 'Termo de autorização assinado')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='termoautorizacao',
            constraint=models.UniqueConstraint(condition=models.Q(('dispensado', False), ('oficio__isnull', False), ('viajante__isnull', False)), fields=('oficio', 'viajante'), name='uniq_termo_oficio_viajante_ativo'),
        ),
        # 9. Adicionar campos extras ao Trecho
        migrations.AddField(
            model_name='trecho',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AddField(
            model_name='trecho',
            name='duracao_minutos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (minutos)'),
        ),
        migrations.AddField(
            model_name='trecho',
            name='is_retorno',
            field=models.BooleanField(default=False, verbose_name='Trecho de retorno'),
        ),
        migrations.AddField(
            model_name='trecho',
            name='tempo_pos_minutos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo auxiliar pós-chegada (min)'),
        ),
        migrations.AddField(
            model_name='trecho',
            name='tempo_pre_minutos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo auxiliar pré-saída (min)'),
        ),
        # 10. Adicionar FKs ao RoteiroDestino
        migrations.AddField(
            model_name='roteirodestino',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiro_destinos', to='viagens.cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiro_destinos', to='viagens.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='roteirodestino',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viagens.roteiro', verbose_name='Roteiro'),
        ),
    ]
