from django.urls import path

from . import views


urlpatterns = [
    path("", views.dashboard_home, name="dashboard_home"),
    path("dashboard/", views.dashboard_home, name="dashboard_home_alt"),
    path("dashboard/data/", views.dashboard_data_api, name="dashboard_data_api"),
    path("efetivo/", views.efetivo, name="efetivo"),
    path("diarias/", views.diarias, name="diarias"),
    path("simulacao-diarias/", views.simulacao_diarias, name="simulacao_diarias"),
    path(
        "simulacao-diarias/calcular/",
        views.simulacao_diarias_calcular,
        name="simulacao_diarias_calcular",
    ),
    path("oficios/novo/", views.formulario, name="formulario"),
    path("oficios/etapa-2/", views.oficio_step2, name="oficio_step2"),
    path("oficios/etapa-3/", views.oficio_step3, name="oficio_step3"),
    path("oficios/calcular-diarias/", views.oficio_calcular_diarias, name="oficio_calcular_diarias"),
    path("oficios/etapa-4/", views.oficio_step4, name="oficio_step4"),
    path("planos-trabalho/", views.planos_trabalho_list, name="planos_trabalho_list"),
    path(
        "planos-trabalho/criar/",
        views.plano_trabalho_criar,
        name="plano_trabalho_criar",
    ),
    path(
        "planos-trabalho/oficio/<int:oficio_id>/editar/",
        views.plano_trabalho_editar,
        name="plano_trabalho_editar",
    ),
    path(
        "planos-trabalho/oficio/<int:oficio_id>/etapa-1/",
        views.plano_trabalho_step1,
        name="plano_trabalho_step1",
    ),
    path(
        "planos-trabalho/oficio/<int:oficio_id>/etapa-2/",
        views.plano_trabalho_step2,
        name="plano_trabalho_step2",
    ),
    path(
        "planos-trabalho/oficio/<int:oficio_id>/etapa-3/",
        views.plano_trabalho_step3,
        name="plano_trabalho_step3",
    ),
    path(
        "planos-trabalho/oficio/<int:oficio_id>/etapa-3/calcular-diarias/",
        views.plano_trabalho_calcular_diarias,
        name="plano_trabalho_calcular_diarias",
    ),
    path(
        "planos-trabalho/oficio/<int:oficio_id>/resumo/",
        views.plano_trabalho_resumo,
        name="plano_trabalho_resumo",
    ),
    path(
        "planos-trabalho/oficio/<int:oficio_id>/docx/",
        views.plano_trabalho_download_docx,
        name="plano_trabalho_download_docx",
    ),
    path(
        "planos-trabalho/oficio/<int:oficio_id>/pdf/",
        views.plano_trabalho_download_pdf,
        name="plano_trabalho_download_pdf",
    ),
    path("ordens-servico/", views.ordens_servico_list, name="ordens_servico_list"),
    path(
        "ordens-servico/criar/",
        views.ordem_servico_criar,
        name="ordem_servico_criar",
    ),
    path(
        "ordens-servico/oficio/<int:oficio_id>/editar/",
        views.ordem_servico_editar,
        name="ordem_servico_editar",
    ),
    path(
        "ordens-servico/oficio/<int:oficio_id>/docx/",
        views.ordem_servico_download_docx,
        name="ordem_servico_download_docx",
    ),
    path(
        "ordens-servico/oficio/<int:oficio_id>/pdf/",
        views.ordem_servico_download_pdf,
        name="ordem_servico_download_pdf",
    ),
    path(
        "oficios/<int:oficio_id>/calcular-diarias/",
        views.oficio_calcular_diarias,
        name="oficio_calcular_diarias_oficio",
    ),
    path(
        "oficios/<int:oficio_id>/rascunho/",
        views.oficio_draft_resume,
        name="oficio_draft_resume",
    ),
    path(
        "oficios/<int:oficio_id>/editar/etapa-1/",
        views.oficio_edit_step1,
        name="oficio_edit_step1",
    ),
    path(
        "oficios/<int:oficio_id>/editar/etapa-2/",
        views.oficio_edit_step2,
        name="oficio_edit_step2",
    ),
    path(
        "oficios/<int:oficio_id>/editar/etapa-3/",
        views.oficio_edit_step3,
        name="oficio_edit_step3",
    ),
    path(
        "oficios/<int:oficio_id>/editar/etapa-4/",
        views.oficio_edit_step4,
        name="oficio_edit_step4",
    ),
    path(
        "oficios/<int:oficio_id>/editar/salvar/",
        views.oficio_edit_save,
        name="oficio_edit_save",
    ),
    path(
        "oficios/<int:oficio_id>/editar/cancelar/",
        views.oficio_edit_cancel,
        name="oficio_edit_cancel",
    ),

    path(
        "oficios/<int:oficio_id>/documentos/",
        views.oficio_documentos,
        name="oficio_documentos",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/fragment/",
        views.oficio_documentos_fragment,
        name="oficio_documentos_fragment",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/gerar_todos/",
        views.oficio_documentos_gerar_todos,
        name="oficio_documentos_gerar_todos",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/justificativa.docx",
        views.oficio_download_justificativa_docx,
        name="oficio_download_justificativa_docx",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/justificativa.pdf",
        views.oficio_download_justificativa_pdf,
        name="oficio_download_justificativa_pdf",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/plano_trabalho.docx",
        views.oficio_download_plano_trabalho_docx,
        name="oficio_download_plano_trabalho_docx",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/plano_trabalho.pdf",
        views.oficio_download_plano_trabalho_pdf,
        name="oficio_download_plano_trabalho_pdf",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/ordem_servico.docx",
        views.oficio_download_ordem_servico_docx,
        name="oficio_download_ordem_servico_docx",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/ordem_servico.pdf",
        views.oficio_download_ordem_servico_pdf,
        name="oficio_download_ordem_servico_pdf",
    ),
    path("oficios/<int:oficio_id>/download-docx/",views.oficio_download_docx,name="oficio_download_docx"),
    path(
        "oficios/<int:oficio_id>/download-termo-autorizacao/",
        views.oficio_download_termo_autorizacao,
        name="oficio_download_termo_autorizacao",
    ),
    path(
        "oficios/<int:oficio_id>/download-termo-autorizacao/pdf/",
        views.oficio_download_termo_autorizacao_pdf,
        name="oficio_download_termo_autorizacao_pdf",
    ),
    path(
        "oficios/<int:oficio_id>/documentos/justificativa/",
        views.oficio_download_justificativa,
        name="oficio_download_justificativa",
    ),
    path("oficios/<int:oficio_id>/download-pdf/", views.oficio_download_pdf, name="oficio_download_pdf"),
    path("api/validacoes/resultado/", views.validacao_resultado, name="validacao_resultado"),
    path("roteiros/", views.roteiro_lista, name="roteiro_lista"),
    path("roteiros/novo/", views.roteiro_novo, name="roteiro_novo"),
    path("roteiros/salvar/", views.roteiro_salvar, name="roteiro_salvar"),
    path("roteiros/<int:pk>/editar/", views.roteiro_editar, name="roteiro_editar"),
    path("roteiros/<int:pk>/excluir/", views.roteiro_excluir, name="roteiro_excluir"),
    path("roteiros/<int:pk>/detalhe/", views.roteiro_detalhe, name="roteiro_detalhe"),
    path("api/roteiros/buscar/", views.api_roteiros_buscar, name="api_roteiros_buscar"),
    path("api/roteiros/<int:pk>/json/", views.api_roteiro_json, name="api_roteiro_json"),
    path(
        "api/roteiros/criar-inline/",
        views.api_roteiro_criar_inline,
        name="api_roteiro_criar_inline",
    ),
    path(
        "api/roteiros/<int:pk>/cards/",
        views.api_roteiro_cards,
        name="api_roteiro_cards",
    ),
    path(
        "api/roteiros/listar/",
        views.roteiros_listar_api,
        name="api_roteiros_listar",
    ),
    path(
        "api/roteiros/salvar/",
        views.api_roteiro_salvar,
        name="api_roteiros_salvar",
    ),
    path(
        "api/roteiros/salvar-legado/",
        views.api_roteiro_salvar,
        name="api_roteiro_salvar",
    ),
    path(
        "oficios/<int:oficio_id>/roteiros/vincular/",
        views.oficio_vincular_roteiro,
        name="oficio_vincular_roteiro",
    ),
    path(
        "oficios/<int:oficio_id>/roteiros/<int:roteiro_id>/desvincular/",
        views.oficio_desvincular_roteiro,
        name="oficio_desvincular_roteiro",
    ),


    path("viajantes/novo/", views.viajante_cadastro, name="viajante_cadastro"),
    path("viajantes/<int:viajante_id>/editar/", views.viajante_editar, name="viajante_editar"),
    path("viajantes/", views.viajantes_lista, name="viajantes_lista"),
    path("veiculos/novo/", views.veiculo_cadastro, name="veiculo_cadastro"),
    path("veiculos/<int:veiculo_id>/editar/", views.veiculo_editar, name="veiculo_editar"),
    path("veiculos/", views.veiculos_lista, name="veiculos_lista"),
    path("oficios/", views.oficios_lista, name="oficios_lista"),
    path(
        "oficios/<int:oficio_id>/pacote-evento/",
        views.evento_redirect_from_oficio,
        name="evento_redirect_from_oficio",
    ),
    path("eventos/", views.eventos_lista, name="eventos_lista"),
    path(
        "eventos/novo-guiado/",
        views.evento_novo_guiado,
        name="evento_novo_guiado",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-1/",
        views.evento_guiado_etapa1,
        name="evento_guiado_etapa1",
    ),
    path(
        "eventos/<int:evento_id>/guiado/painel/",
        views.evento_guiado_painel,
        name="evento_guiado_painel",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-2/",
        views.evento_guiado_etapa2,
        name="evento_guiado_etapa2",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-3/",
        views.evento_guiado_etapa3,
        name="evento_guiado_etapa3",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-4/",
        views.evento_guiado_etapa4,
        name="evento_guiado_etapa4",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-4/criar-plano/",
        views.evento_guiado_etapa4_criar_plano,
        name="evento_guiado_etapa4_criar_plano",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-4/criar-ordem/",
        views.evento_guiado_etapa4_criar_ordem,
        name="evento_guiado_etapa4_criar_ordem",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-5/",
        views.evento_guiado_etapa5,
        name="evento_guiado_etapa5",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-5/gerar-lote/",
        views.evento_guiado_etapa5_gerar_lote,
        name="evento_guiado_etapa5_gerar_lote",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-5/dispensar/",
        views.evento_guiado_etapa5_dispensar,
        name="evento_guiado_etapa5_dispensar",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-6/",
        views.evento_guiado_etapa6,
        name="evento_guiado_etapa6",
    ),
    path(
        "eventos/<int:evento_id>/guiado/exportar-zip/",
        views.evento_guiado_exportar_zip,
        name="evento_guiado_exportar_zip",
    ),
    path(
        "eventos/<int:evento_id>/guiado/etapa-<int:etapa_num>/",
        views.evento_guiado_etapa_placeholder,
        name="evento_guiado_etapa_placeholder",
    ),
    path(
        "eventos/<int:evento_id>/pacote/",
        views.evento_pacote,
        name="evento_pacote",
    ),
    path(
        "eventos/<int:evento_id>/pacote/upload-assinado/",
        views.evento_upload_assinado,
        name="evento_upload_assinado",
    ),
    path(
        "eventos/<int:evento_id>/pacote/remover-assinado/<int:arquivo_id>/",
        views.evento_remover_assinado,
        name="evento_remover_assinado",
    ),
    path(
        "eventos/<int:evento_id>/pacote/gerar-pdf-protocolo/",
        views.evento_gerar_pdf_protocolo,
        name="evento_gerar_pdf_protocolo",
    ),
    path(
        "eventos/<int:evento_id>/pacote/download-compilado/",
        views.evento_download_compilado,
        name="evento_download_compilado",
    ),
    path(
        "justificativas/",
        views.justificativas_lista,
        name="justificativas_lista",
    ),
    path(
        "justificativas/oficio/<int:oficio_id>/",
        views.justificativa_oficio,
        name="justificativa_oficio",
    ),
    path(
        "justificativas/nova/",
        views.gerador_justificativas,
        name="justificativa_nova",
    ),
    path(
        "documentos/gerador-justificativas/",
        views.gerador_justificativas,
        name="gerador_justificativas",
    ),
    path(
        "documentos/modelos-justificativa/",
        views.modelos_justificativa_lista,
        name="modelos_justificativa_lista",
    ),
    path(
        "documentos/modelos-justificativa/novo/",
        views.modelo_justificativa_criar,
        name="modelo_justificativa_criar",
    ),
    path(
        "documentos/modelos-justificativa/<int:pk>/editar/",
        views.modelo_justificativa_editar,
        name="modelo_justificativa_editar",
    ),
    path(
        "documentos/modelos-justificativa/<int:pk>/definir-padrao/",
        views.modelo_justificativa_definir_padrao,
        name="modelo_justificativa_definir_padrao",
    ),
    path(
        "documentos/modelos-justificativa/<int:pk>/salvar-como-novo/",
        views.modelo_justificativa_salvar_como_novo,
        name="modelo_justificativa_salvar_como_novo",
    ),
    path(
        "documentos/modelos-justificativa/<int:pk>/excluir/",
        views.modelo_justificativa_excluir,
        name="modelo_justificativa_excluir",
    ),
    path(
        "api/modelos-justificativa/<int:pk>/texto/",
        views.modelo_justificativa_texto_api,
        name="modelo_justificativa_texto_api",
    ),
    path(
        "termos-autorizacao/",
        views.termos_autorizacao_lista,
        name="termos_autorizacao_lista",
    ),
    path(
        "termos-autorizacao/novo/",
        views.termo_autorizacao_cadastro,
        name="termo_autorizacao_cadastro",
    ),
    path(
        "termos-autorizacao/novo-contexto/",
        views.termo_autorizacao_cadastro_contextual,
        name="termo_autorizacao_cadastro_contextual",
    ),
    path(
        "termos-autorizacao/<int:termo_id>/download-docx/",
        views.termo_autorizacao_download_docx,
        name="termo_autorizacao_download_docx",
    ),
    path(
        "termos-autorizacao/<int:termo_id>/download-pdf/",
        views.termo_autorizacao_download_pdf,
        name="termo_autorizacao_download_pdf",
    ),
    path("oficios/<int:oficio_id>/excluir/", views.oficio_excluir, name="oficio_excluir"),
    path("configuracoes/oficio/", views.configuracoes_oficio, name="config_oficio"),
    path("api/viajantes/", views.viajantes_api, name="viajantes_api"),
    path("api/veiculo/", views.veiculo_api, name="veiculo_api"),
    path("api/cidades/", views.api_cidades_por_estado, name="api_cidades_por_estado"),
    path("api/ufs/", views.ufs_api, name="api_ufs"),
    path("api/cidades-busca/", views.cidades_busca_api, name="api_cidades_busca"),
    path("api/cidades-por-estado/", views.cidades_api, name="cidades_api"),
    path("api/servidores/", views.servidores_api, name="servidores_api"),
    path(
        "api/coordenadores-municipais/",
        views.coordenadores_municipais_api,
        name="coordenadores_municipais_api",
    ),
    path("api/assinantes/", views.assinantes_api, name="assinantes_api"),
    path("api/motoristas/", views.motoristas_api, name="motoristas_api"),
    path("api/cep/<str:cep>/", views.cep_api, name="cep_api"),
    path("api/servidores/<int:servidor_id>/", views.servidor_detail_api, name="servidor_detail_api"),
    path("api/motoristas/<int:motorista_id>/", views.motorista_detail_api, name="motorista_detail_api"),
    path("api/veiculos/", views.veiculos_busca_api, name="veiculos_busca_api"),
    path("api/veiculos/<int:veiculo_id>/", views.veiculo_detail_api, name="veiculo_detail_api"),
    path("api/oficio-motorista-referencia/", views.oficio_motorista_referencia, name="oficio_motorista_referencia"),
    path("cargos/criar/", views.cargo_criar, name="cargo_criar"),
    path("modal/viajantes/novo/", views.modal_viajante_form, name="modal_viajante_form"),
    path("modal/veiculos/novo/", views.modal_veiculo_form, name="modal_veiculo_form"),
]
